### ISSUE TITLE
infection

### ISSUE THREAD

**Issue by philshepard** [etresoft/EtreCheck#3]
As of a few minutes ago, the download from your website is infected with Adware.

http://www.etresoft.com/download/EtreCheck.zip

Could you replace the download with a clean file?  Thank you so much for your utility.

**Comment by etresoft** [comment]
Nope. It isn't. Can you tell me what AV software told you that and why? EtreCheck's adware list is intentionally compressed and corrupted so that AV software won't see all of EtreCheck's adware filename signatures. If I have missed something or need to actually encrypt the file instead, I would like to know. Thanks.

**Comment by etresoft** [comment]
I seem to have included some strings like "Genieo" in the source. That was a long time ago now. But I'm not even using those strings in the new version so I removed them. Hopefully it doesn't trip the AV software anymore.
