### ISSUE TITLE
kaspersky  NOT adware

### ISSUE THREAD

**Issue by DG12** [etresoft/EtreCheck#98]
kaspersky
Unknown file: /Library/LaunchAgents/com.kaspersky.safekids.gui.plist
    	/Library/Application Support/Kaspersky Lab/SafeKids/Applications/Kaspersky Safe Kids Agent.app/Contents/MacOS/safekids_agent -autolaunch 1
    One possible adware file found. [Remove/Report]

not adware

Thank you

**Comment by etresoft** [comment]
Since you created an issue for this, I will add it to the whitelist. 

However, you should know that the entire whitelist is going away. It is not possible to distinguish the above file from adware or malware. The executable does not have a digital signature. Without that, it could be something malicious masquerading as Kaspersky. There is no way for EtreCheck to tell the difference. 

A future version of EtreCheck will handle these unknown files differently. There will be no whitelist and any app that doesn't have a signature will be flagged as possible malware. End users will be able to whitelist such files only on their own machines.

I encourage you to contact Kaspersky and encourage them to start signing their apps.

**Comment by DG12** [comment]
Thanks
